[package]
name = "many_instr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.21"
borsh = "1.5"
borsh-derive = "1.5"

[features]
default = []